### PR TITLE
fix a no-used var

### PR DESCRIPTION
**Pull request by hjlarry**
seems declared but not use it

### CODE REVIEW

**Comment by thblt** [comment]
Thank you! Could you please also update the source file, `write-yourself-a-git.org`?

**Comment by hjlarry** [comment]
ok, by the way,
```
hashRE = re.compile(r"^[0-9A-Fa-f]{1,16}$")
...
if hashRE.match(name):
        if len(name) == 40:
            # This is a complete hash
            return [name.lower()]
```
This is not work for me. Is it should be `re.compile(r"^[0-9A-Fa-f]{1,40}$")` ?

**Comment by thblt** [comment]
Err, of course, thanks again! Actually, it should even be

```
re.compile(r"^[0-9A-Fa-f]{4,40}$")
```

**Comment by thblt** [comment]
(If you can, could you add a test to check that 40-char hashes work?)

**Comment by hjlarry** [comment]
ok, I will do that later

**Comment by hjlarry** [comment]
done!

**Comment by thblt** [comment]
Thanks again!

**Pull request merged**
